Compute program_logger before the closure
It should be slightly faster and avoid:

Error in sys.excepthook:
Traceback (most recent call last):
  File "daiquiri/__init__.py", line 88, in logging_excepthook
    logging.getLogger(program_name).critical(
AttributeError: 'NoneType' object has no attribute 'getLogger'

Which does not make sense either, but whatever Python.